feat: list subcommand
sern-handler/cli pull request #113
Opened 2023-08-27 15:46 UTC by EvolutionX-10

2023-08-27 16:00 UTC, SrIzan10 approved these changes

2023-08-27 16:17 UTC, jacoobes requested changes

2023-08-27 16:17 UTC, jacoobes commented on src/index.ts
> +        new Command(list.name) //
Merge build app cli first into main, then modify the command to lazily load list command

2023-08-31 19:52 UTC, jacoobes commented on src/utilities/preprocessor.ts
> +            moduleResolution: 'bundler',
ill do this

2023-08-31 20:07 UTC, merged