fix: multiple bugs
sern-handler/cli pull request #119
Opened 2023-09-24 18:05 UTC by jacoobes

2023-09-27 04:23 UTC, EvolutionX-10 requested changes

2023-09-27 04:23 UTC, EvolutionX-10 commented on src/create-publish.mts
> -    if (res.status === 429) {
are you going to add case for 429?

2023-09-27 15:23 UTC, jacoobes commented on src/create-publish.mts
> -    if (res.status === 429) {
good catch, im stupid

2023-10-05 06:47 UTC, EvolutionX-10 approved these changes

2023-10-05 06:48 UTC, merged