feat: add default settings for the -y flag
sern-handler/cli pull request #19
Opened 2022-05-11 17:46 UTC by Allyedge

Added default settings for the `-y` flag.

2022-05-11 17:53 UTC, EvolutionX-10 requested changes
it shouldn't ask these except maybe project name is fine
![image](https://user-images.githubusercontent.com/85353424/167914728-a3e7a994-9485-42c9-93c1-5aeff3139c32.png)
npm is default, git is initialised by default

2022-05-11 17:53 UTC, Allyedge commented
> it shouldn't ask these except maybe project name is fine ![image](https://user-images.githubusercontent.com/85353424/167914728-a3e7a994-9485-42c9-93c1-5aeff3139c32.png) npm is default, git is initialised by default

Alright, working on it.

2022-05-11 18:37 UTC, jacoobes submitted a review, later dismissed

2022-05-12 03:06 UTC, EvolutionX-10 requested changes

2022-05-12 03:06 UTC, EvolutionX-10 commented on src/commands/init.js
> +	if (!isDefault && Object.keys(data).length < 5) process.exit(1);
why `!isDefault` is needed?
even when the defaults are used, data object is getting all 5 properties needed

2022-05-12 03:06 UTC, EvolutionX-10 commented on src/commands/init.js
> +	}
```suggestion
	isDefault ? git_init.gitInit = true : git_init = await prompt([gitInit])
```
how about this

2022-05-12 03:06 UTC, EvolutionX-10 commented on src/commands/init.js
> +	}
```suggestion
	let pm;
	isDefault ? pm = 'npm' : await npm()
```

2022-05-12 18:35 UTC, Allyedge commented
Looks good.

2022-05-13 05:14 UTC, EvolutionX-10 approved these changes

2022-05-13 05:39 UTC, merged