Option to skip package manager selection
sern-handler/cli pull request #20
Opened 2022-05-12 07:31 UTC by qxb3

2022-05-12 08:04 UTC, EvolutionX-10 commented
There's a problem, it only prompts for manager if a user has both, yarn and npm
Else it will just continue installing with what the user has
Here are the [lines](https://github.com/sern-handler/cli/blob/main/src/commands/init.js#L69-L78) that indicate the logic
If you got any ideas to fix it, feel free to do

2022-05-12 08:37 UTC, qxb3 commented
@EvolutionX-10 can you try it now?

2022-05-12 09:18 UTC, Allyedge commented
I suggest waiting until #19 is merged. So that there won't be any conflicts.

I will review the PR after that.

2022-05-13 09:41 UTC, EvolutionX-10 commented on src/prompts/init.js
> +	message: `Do you want ${blueBright('me')} to install dependecies?`,
```suggestion
	message: `Do you want ${blueBright('me')} to install dependencies?`,
```
Typo

2022-05-13 09:42 UTC, EvolutionX-10 requested changes
I'll test them soon

2022-05-13 12:25 UTC, Allyedge submitted a review, later dismissed
Everything looks fine, good job.

2022-05-14 04:12 UTC, EvolutionX-10 approved these changes
Nice @qxb3

2022-05-14 04:12 UTC, merged