Rewrite to typescript
sern-handler/cli pull request #74
Opened 2022-08-27 11:50 UTC by Tofix26

2022-08-27 13:33 UTC, SrIzan10 commented
Did you run prettier?

2022-08-27 13:46 UTC, Murtatrxx approved these changes
🎊

2022-08-27 15:02 UTC, SrIzan10 approved these changes

2022-08-28 08:24 UTC, SrIzan10 commented
@EvolutionX-10 is going to have a good time reading this pr lol

2022-08-28 15:43 UTC, Tofix26 commented
> Did you run prettier?

Didn't before but now fixed it

2022-08-28 16:28 UTC, SrIzan10 commented
Ok nice

2022-08-28 16:35 UTC, jacoobes requested changes

2022-08-28 16:35 UTC, jacoobes commented on src/commands/init.ts
> +interface flags {
types convention is PascalCase, flags -> Flags

2022-08-28 16:35 UTC, jacoobes commented on tsconfig.json
>  {
Should we generate d.ts files?
(setting declaration: true)

2022-08-28 16:35 UTC, jacoobes commented on src/commands/init.ts
> +interface data {
same here, PascalCase convention

2022-08-28 16:35 UTC, jacoobes commented on package.json
>  	"version": "0.4.2",
bump cur -> 0.5.2

2022-08-28 16:42 UTC, Murtatrxx commented
Consider using conventional commits.

2022-08-28 16:42 UTC, Murtatrxx submitted a review, later dismissed

2022-08-28 16:44 UTC, Tofix26 commented
> Consider using conventional commits.

forgot again :p

2022-08-28 16:44 UTC, Murtatrxx submitted a review, later dismissed

2022-09-03 06:05 UTC, EvolutionX-10 requested changes

2022-09-03 18:56 UTC, Tofix26 commented on package.json
> +	"version": "0.5",
done

2022-09-04 02:24 UTC, EvolutionX-10 requested changes

2022-09-04 02:24 UTC, EvolutionX-10 commented on src/commands/init.ts
> +	sync: string;
```suggestion
	y: boolean;
	sync: boolean;
```

2022-09-05 15:18 UTC, Tofix26 commented
fixed ^

2022-09-06 00:40 UTC, EvolutionX-10 requested changes
probably the final changes

2022-09-06 00:40 UTC, EvolutionX-10 commented on src/commands/init.ts
>  	let git_init;
can you specify their types?

2022-09-06 00:40 UTC, EvolutionX-10 commented on src/commands/init.ts
>  		const projectName = await prompt([name]);
type!

2022-09-06 00:40 UTC, EvolutionX-10 commented on src/commands/init.ts
>  	let choice;
type!

2022-09-06 00:40 UTC, EvolutionX-10 commented on src/commands/init.ts
> +}
shift all the type definitions and interfaces at the bottom of the file

2022-09-06 00:40 UTC, EvolutionX-10 commented on src/prompts/init.ts
>  export const lang = {
put the type PromptObject on every exported object

2022-09-06 00:40 UTC, EvolutionX-10 commented on src/prompts/plugin.ts
> +	}
shift it to bottom of the file and rename it to `Data`

2022-09-06 00:40 UTC, EvolutionX-10 commented on tsconfig.json
> +		"moduleResolution": "node",
```suggestion
		"moduleResolution": "Node",
```

2022-09-06 14:16 UTC, EvolutionX-10 requested changes

2022-09-06 14:16 UTC, EvolutionX-10 commented on src/commands/init.ts
> +	} as PromptData;
why not just this?
```suggestion
	let data: PromptData;
```

2022-09-06 14:31 UTC, EvolutionX-10 requested changes

2022-09-06 14:31 UTC, EvolutionX-10 commented on src/prompts/plugin.ts
> +function upperCase(string: string) {
```suggestion
function upperCase(string: string | null) {
```

And in 
https://github.com/Tofix26/sern-cli-ts-rewrite/blob/e0dd4af7f2ee609aa02f0ef07a461119bd3e6752/src/utilities/getLang.ts#L4-L8

Make it return type `Promise<string>` and you can remove the jsdoc type

2022-09-07 04:44 UTC, jacoobes requested changes

2022-09-07 04:44 UTC, jacoobes commented on src/utilities/install.ts
> +	choice: 'skip' | 'npm' | 'yarn',
could we lift this into a new type called PackageManagerChoice = 'skip' | 'npm' | 'yarn',
this type is stated twice here and https://github.com/sern-handler/cli/pull/74/files#r963771486

2022-09-09 03:48 UTC, jacoobes submitted a review, later dismissed

2022-09-13 04:31 UTC, EvolutionX-10 approved these changes
For future me: Learn how to push effectively in other's branches for PRs

2022-09-13 04:35 UTC, merged